///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllCategoryModelDataChildLinksUp {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
}
*/

  String? href;

  AllCategoryModelDataChildLinksUp({
    this.href,
  });

  AllCategoryModelDataChildLinksUp.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataChildLinksCollection {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
}
*/

  String? href;

  AllCategoryModelDataChildLinksCollection({
    this.href,
  });

  AllCategoryModelDataChildLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataChildLinksSelf {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/211"
}
*/

  String? href;

  AllCategoryModelDataChildLinksSelf({
    this.href,
  });

  AllCategoryModelDataChildLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataChildLinks {
/*
{
  "self": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/211"
    }
  ],
  "collection": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
    }
  ],
  "up": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
    }
  ]
}
*/

  List<AllCategoryModelDataChildLinksSelf?>? self;
  List<AllCategoryModelDataChildLinksCollection?>? collection;
  List<AllCategoryModelDataChildLinksUp?>? up;

  AllCategoryModelDataChildLinks({
    this.self,
    this.collection,
    this.up,
  });

  AllCategoryModelDataChildLinks.fromJson(Map<String, dynamic> json) {
    if (json['self'] != null) {
      final v = json['self'];
      final arr0 = <AllCategoryModelDataChildLinksSelf>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataChildLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json['collection'] != null) {
      final v = json['collection'];
      final arr0 = <AllCategoryModelDataChildLinksCollection>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataChildLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
    if (json['up'] != null) {
      final v = json['up'];
      final arr0 = <AllCategoryModelDataChildLinksUp>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataChildLinksUp.fromJson(v));
      });
      up = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      final v = self;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['self'] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['collection'] = arr0;
    }
    if (up != null) {
      final v = up;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['up'] = arr0;
    }
    return data;
  }
}

class AllCategoryModelDataChild {
/*
{
  "id": 211,
  "name": "test",
  "slug": "test-accessories-2",
  "parent": 198,
  "description": "",
  "display": "default",
  "image": null,
  "menu_order": 0,
  "count": 0,
  "_links": {
    "self": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/211"
      }
    ],
    "collection": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
      }
    ],
    "up": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
      }
    ]
  }
}
*/

  int? id;
  String? name;
  String? slug;
  int? parent;
  String? description;
  String? display;
  Image? image;
  int? menuOrder;
  int? count;
  AllCategoryModelDataChildLinks? Links;

  AllCategoryModelDataChild({
    this.id,
    this.name,
    this.slug,
    this.parent,
    this.description,
    this.display,
    this.image,
    this.menuOrder,
    this.count,
    this.Links,
  });

  AllCategoryModelDataChild.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    slug = json['slug']?.toString();
    parent = json['parent']?.toInt();
    description = json['description']?.toString();
    display = json['display']?.toString();
    image = json['image'] != null ? Image.fromJson(json['image']) : null;
    menuOrder = json['menu_order']?.toInt();
    count = json['count']?.toInt();
    Links =
        (json['_links'] != null) ? AllCategoryModelDataChildLinks.fromJson(json['_links']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['slug'] = slug;
    data['parent'] = parent;
    data['description'] = description;
    data['display'] = display;
    data['image'] = image;
    data['menu_order'] = menuOrder;
    data['count'] = count;
    if (Links != null) {
      data['_links'] = Links!.toJson();
    }
    return data;
  }
}

class AllCategoryModelDataParentLinksCollection {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
}
*/

  String? href;

  AllCategoryModelDataParentLinksCollection({
    this.href,
  });

  AllCategoryModelDataParentLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataParentLinksSelf {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
}
*/

  String? href;

  AllCategoryModelDataParentLinksSelf({
    this.href,
  });

  AllCategoryModelDataParentLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataParentLinks {
/*
{
  "self": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
    }
  ],
  "collection": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
    }
  ]
}
*/

  List<AllCategoryModelDataParentLinksSelf?>? self;
  List<AllCategoryModelDataParentLinksCollection?>? collection;

  AllCategoryModelDataParentLinks({
    this.self,
    this.collection,
  });

  AllCategoryModelDataParentLinks.fromJson(Map<String, dynamic> json) {
    if (json['self'] != null) {
      final v = json['self'];
      final arr0 = <AllCategoryModelDataParentLinksSelf>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataParentLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json['collection'] != null) {
      final v = json['collection'];
      final arr0 = <AllCategoryModelDataParentLinksCollection>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataParentLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      final v = self;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['self'] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['collection'] = arr0;
    }
    return data;
  }
}

class AllCategoryModelDataParentImage {
/*
{
  "id": 5673,
  "date_created": "2024-01-25T10:40:34",
  "date_created_gmt": "2024-01-25T10:40:34",
  "date_modified": "2024-01-25T10:40:34",
  "date_modified_gmt": "2024-01-25T10:40:34",
  "src": "https://localfirst.testdevteam.xyz/wp-content/uploads/2024/01/accessories.jpg",
  "name": "accessories",
  "alt": ""
}
*/

  int? id;
  String? dateCreated;
  String? dateCreatedGmt;
  String? dateModified;
  String? dateModifiedGmt;
  String? src;
  String? name;
  String? alt;

  AllCategoryModelDataParentImage({
    this.id,
    this.dateCreated,
    this.dateCreatedGmt,
    this.dateModified,
    this.dateModifiedGmt,
    this.src,
    this.name,
    this.alt,
  });

  AllCategoryModelDataParentImage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    dateCreated = json['date_created']?.toString();
    dateCreatedGmt = json['date_created_gmt']?.toString();
    dateModified = json['date_modified']?.toString();
    dateModifiedGmt = json['date_modified_gmt']?.toString();
    src = json['src']?.toString();
    name = json['name']?.toString();
    alt = json['alt']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['date_created'] = dateCreated;
    data['date_created_gmt'] = dateCreatedGmt;
    data['date_modified'] = dateModified;
    data['date_modified_gmt'] = dateModifiedGmt;
    data['src'] = src;
    data['name'] = name;
    data['alt'] = alt;
    return data;
  }
}

class AllCategoryModelDataParent {
/*
{
  "id": 198,
  "name": "Accessories",
  "slug": "accessories-2",
  "parent": 0,
  "description": "",
  "display": "default",
  "image": {
    "id": 5673,
    "date_created": "2024-01-25T10:40:34",
    "date_created_gmt": "2024-01-25T10:40:34",
    "date_modified": "2024-01-25T10:40:34",
    "date_modified_gmt": "2024-01-25T10:40:34",
    "src": "https://localfirst.testdevteam.xyz/wp-content/uploads/2024/01/accessories.jpg",
    "name": "accessories",
    "alt": ""
  },
  "menu_order": 0,
  "count": 11,
  "_links": {
    "self": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
      }
    ],
    "collection": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
      }
    ]
  }
}
*/

  int? id;
  String? name;
  String? slug;
  int? parent;
  String? description;
  String? display;
  AllCategoryModelDataParentImage? image;
  int? menuOrder;
  int? count;
  AllCategoryModelDataParentLinks? Links;

  AllCategoryModelDataParent({
    this.id,
    this.name,
    this.slug,
    this.parent,
    this.description,
    this.display,
    this.image,
    this.menuOrder,
    this.count,
    this.Links,
  });

  AllCategoryModelDataParent.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    slug = json['slug']?.toString();
    parent = json['parent']?.toInt();
    description = json['description']?.toString();
    display = json['display']?.toString();
    image =
        (json['image'] != null) ? AllCategoryModelDataParentImage.fromJson(json['image']) : null;
    menuOrder = json['menu_order']?.toInt();
    count = json['count']?.toInt();
    Links =
        (json['_links'] != null) ? AllCategoryModelDataParentLinks.fromJson(json['_links']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['slug'] = slug;
    data['parent'] = parent;
    data['description'] = description;
    data['display'] = display;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['menu_order'] = menuOrder;
    data['count'] = count;
    if (Links != null) {
      data['_links'] = Links!.toJson();
    }
    return data;
  }
}

class AllCategoryModelData {
/*
{
  "parent": {
    "id": 198,
    "name": "Accessories",
    "slug": "accessories-2",
    "parent": 0,
    "description": "",
    "display": "default",
    "image": {
      "id": 5673,
      "date_created": "2024-01-25T10:40:34",
      "date_created_gmt": "2024-01-25T10:40:34",
      "date_modified": "2024-01-25T10:40:34",
      "date_modified_gmt": "2024-01-25T10:40:34",
      "src": "https://localfirst.testdevteam.xyz/wp-content/uploads/2024/01/accessories.jpg",
      "name": "accessories",
      "alt": ""
    },
    "menu_order": 0,
    "count": 11,
    "_links": {
      "self": [
        {
          "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
        }
      ],
      "collection": [
        {
          "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
        }
      ]
    }
  },
  "child": [
    {
      "id": 211,
      "name": "test",
      "slug": "test-accessories-2",
      "parent": 198,
      "description": "",
      "display": "default",
      "image": null,
      "menu_order": 0,
      "count": 0,
      "_links": {
        "self": [
          {
            "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/211"
          }
        ],
        "collection": [
          {
            "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
          }
        ],
        "up": [
          {
            "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
          }
        ]
      }
    }
  ]
}
*/

  AllCategoryModelDataParent? parent;
  List<AllCategoryModelDataChild?>? child;

  AllCategoryModelData({
    this.parent,
    this.child,
  });

  AllCategoryModelData.fromJson(Map<String, dynamic> json) {
    parent = (json['parent'] != null) ? AllCategoryModelDataParent.fromJson(json['parent']) : null;
    if (json['child'] != null) {
      final v = json['child'];
      final arr0 = <AllCategoryModelDataChild>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataChild.fromJson(v));
      });
      child = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (parent != null) {
      data['parent'] = parent!.toJson();
    }
    if (child != null) {
      final v = child;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['child'] = arr0;
    }
    return data;
  }
}

class AllCategoryModel {
/*
{
  "success": true,
  "message": "Category list",
  "code": 200,
  "data": [
    {
      "parent": {
        "id": 198,
        "name": "Accessories",
        "slug": "accessories-2",
        "parent": 0,
        "description": "",
        "display": "default",
        "image": {
          "id": 5673,
          "date_created": "2024-01-25T10:40:34",
          "date_created_gmt": "2024-01-25T10:40:34",
          "date_modified": "2024-01-25T10:40:34",
          "date_modified_gmt": "2024-01-25T10:40:34",
          "src": "https://localfirst.testdevteam.xyz/wp-content/uploads/2024/01/accessories.jpg",
          "name": "accessories",
          "alt": ""
        },
        "menu_order": 0,
        "count": 11,
        "_links": {
          "self": [
            {
              "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
            }
          ],
          "collection": [
            {
              "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
            }
          ]
        }
      },
      "child": [
        {
          "id": 211,
          "name": "test",
          "slug": "test-accessories-2",
          "parent": 198,
          "description": "",
          "display": "default",
          "image": null,
          "menu_order": 0,
          "count": 0,
          "_links": {
            "self": [
              {
                "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/211"
              }
            ],
            "collection": [
              {
                "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories"
              }
            ],
            "up": [
              {
                "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/categories/198"
              }
            ]
          }
        }
      ]
    }
  ]
}
*/

  bool? success;
  String? message;
  int? code;
  List<AllCategoryModelData?>? data;

  AllCategoryModel({
    this.success,
    this.message,
    this.code,
    this.data,
  });

  AllCategoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    code = json['code']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AllCategoryModelData>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelData.fromJson(v));
      });
      data = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['code'] = code;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
class Image {
  int? id;
  String? dateCreated;
  String? dateCreatedGmt;
  String? dateModified;
  String? dateModifiedGmt;
  String? src;
  String? name;
  String? alt;

  Image(
      {this.id,
        this.dateCreated,
        this.dateCreatedGmt,
        this.dateModified,
        this.dateModifiedGmt,
        this.src,
        this.name,
        this.alt});

  Image.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    dateCreated = json['date_created'];
    dateCreatedGmt = json['date_created_gmt'];
    dateModified = json['date_modified'];
    dateModifiedGmt = json['date_modified_gmt'];
    src = json['src'];
    name = json['name'];
    alt = json['alt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['date_created'] = this.dateCreated;
    data['date_created_gmt'] = this.dateCreatedGmt;
    data['date_modified'] = this.dateModified;
    data['date_modified_gmt'] = this.dateModifiedGmt;
    data['src'] = this.src;
    data['name'] = this.name;
    data['alt'] = this.alt;
    return data;
  }
}
