///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class AllCategoryModelDataLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  AllCategoryModelDataLinks({
    this.url,
    this.label,
    this.active,
  });

  AllCategoryModelDataLinks.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    label = json['label']?.toString();
    active = json['active'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['label'] = label;
    data['active'] = active;
    return data;
  }
}

class AllCategoryModelDataDataLinksUp {
/*
{
  "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/150"
}
*/

  String? href;

  AllCategoryModelDataDataLinksUp({
    this.href,
  });

  AllCategoryModelDataDataLinksUp.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataDataLinksCollection {
/*
{
  "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories"
}
*/

  String? href;

  AllCategoryModelDataDataLinksCollection({
    this.href,
  });

  AllCategoryModelDataDataLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataDataLinksSelf {
/*
{
  "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/153"
}
*/

  String? href;

  AllCategoryModelDataDataLinksSelf({
    this.href,
  });

  AllCategoryModelDataDataLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class AllCategoryModelDataDataLinks {
/*
{
  "self": [
    {
      "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/153"
    }
  ],
  "collection": [
    {
      "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories"
    }
  ],
  "up": [
    {
      "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/150"
    }
  ]
}
*/

  List<AllCategoryModelDataDataLinksSelf?>? self;
  List<AllCategoryModelDataDataLinksCollection?>? collection;
  List<AllCategoryModelDataDataLinksUp?>? up;

  AllCategoryModelDataDataLinks({
    this.self,
    this.collection,
    this.up,
  });

  AllCategoryModelDataDataLinks.fromJson(Map<String, dynamic> json) {
    if (json['self'] != null) {
      final v = json['self'];
      final arr0 = <AllCategoryModelDataDataLinksSelf>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataDataLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json['collection'] != null) {
      final v = json['collection'];
      final arr0 = <AllCategoryModelDataDataLinksCollection>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataDataLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
    if (json['up'] != null) {
      final v = json['up'];
      final arr0 = <AllCategoryModelDataDataLinksUp>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataDataLinksUp.fromJson(v));
      });
      up = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      final v = self;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['self'] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['collection'] = arr0;
    }
    if (up != null) {
      final v = up;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['up'] = arr0;
    }
    return data;
  }
}

class AllCategoryModelDataData {
/*
{
  "id": 153,
  "name": "Accessories",
  "slug": "accessories-kids",
  "parent": 150,
  "description": "",
  "display": "default",
  "image": null,
  "menu_order": 0,
  "count": 1,
  "_links": {
    "self": [
      {
        "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/153"
      }
    ],
    "collection": [
      {
        "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories"
      }
    ],
    "up": [
      {
        "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/150"
      }
    ]
  }
}
*/

  int? id;
  String? name;
  String? slug;
  int? parent;
  String? description;
  String? display;
  Image? image;
  int? menuOrder;
  int? count;
  AllCategoryModelDataDataLinks? Links;

  AllCategoryModelDataData({
    this.id,
    this.name,
    this.slug,
    this.parent,
    this.description,
    this.display,
    this.image,
    this.menuOrder,
    this.count,
    this.Links,
  });

  AllCategoryModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    slug = json['slug']?.toString();
    parent = json['parent']?.toInt();
    description = json['description']?.toString();
    display = json['display']?.toString();
    image = json['image'] != null ? Image.fromJson(json['image']) : null;
    menuOrder = json['menu_order']?.toInt();
    count = json['count']?.toInt();
    Links =
        (json['_links'] != null) ? AllCategoryModelDataDataLinks.fromJson(json['_links']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['slug'] = slug;
    data['parent'] = parent;
    data['description'] = description;
    data['display'] = display;
    data['image'] = image;
    data['menu_order'] = menuOrder;
    data['count'] = count;
    if (Links != null) {
      data['_links'] = Links!.toJson();
    }
    return data;
  }
}

class AllCategoryModelData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 153,
      "name": "Accessories",
      "slug": "accessories-kids",
      "parent": 150,
      "description": "",
      "display": "default",
      "image": null,
      "menu_order": 0,
      "count": 1,
      "_links": {
        "self": [
          {
            "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/153"
          }
        ],
        "collection": [
          {
            "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories"
          }
        ],
        "up": [
          {
            "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/150"
          }
        ]
      }
    }
  ],
  "first_page_url": "/?page=1",
  "from": 1,
  "last_page": 2,
  "last_page_url": "/?page=2",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": "/?page=2",
  "path": "/",
  "per_page": 5,
  "prev_page_url": null,
  "to": 5,
  "total": 10
}
*/

  int? currentPage;
  List<AllCategoryModelDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<AllCategoryModelDataLinks?>? links;
  String? nextPageUrl;
  String? path;
  String? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  AllCategoryModelData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });

  AllCategoryModelData.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AllCategoryModelDataData>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json['first_page_url']?.toString();
    from = json['from']?.toInt();
    lastPage = json['last_page']?.toInt();
    lastPageUrl = json['last_page_url']?.toString();
    if (json['links'] != null) {
      final v = json['links'];
      final arr0 = <AllCategoryModelDataLinks>[];
      v.forEach((v) {
        arr0.add(AllCategoryModelDataLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json['next_page_url']?.toString();
    path = json['path']?.toString();
    perPage = json['per_page']?.toString();
    prevPageUrl = json['prev_page_url']?.toString();
    to = json['to']?.toInt();
    total = json['total']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['first_page_url'] = firstPageUrl;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['last_page_url'] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['links'] = arr0;
    }
    data['next_page_url'] = nextPageUrl;
    data['path'] = path;
    data['per_page'] = perPage;
    data['prev_page_url'] = prevPageUrl;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class AllCategoryModel {
/*
{
  "success": true,
  "message": "Category list",
  "code": 200,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 153,
        "name": "Accessories",
        "slug": "accessories-kids",
        "parent": 150,
        "description": "",
        "display": "default",
        "image": null,
        "menu_order": 0,
        "count": 1,
        "_links": {
          "self": [
            {
              "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/153"
            }
          ],
          "collection": [
            {
              "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories"
            }
          ],
          "up": [
            {
              "href": "https://localfirst.rlogical.com/wp-json/wc/v3/products/categories/150"
            }
          ]
        }
      }
    ],
    "first_page_url": "/?page=1",
    "from": 1,
    "last_page": 2,
    "last_page_url": "/?page=2",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": "/?page=2",
    "path": "/",
    "per_page": 5,
    "prev_page_url": null,
    "to": 5,
    "total": 10
  }
}
*/

  bool? success;
  String? message;
  int? code;
  AllCategoryModelData? data;

  AllCategoryModel({
    this.success,
    this.message,
    this.code,
    this.data,
  });

  AllCategoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    code = json['code']?.toInt();
    data = (json['data'] != null) ? AllCategoryModelData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['code'] = code;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Image {
  int? id;
  String? dateCreated;
  String? dateCreatedGmt;
  String? dateModified;
  String? dateModifiedGmt;
  String? src;
  String? name;
  String? alt;

  Image(
      {this.id,
      this.dateCreated,
      this.dateCreatedGmt,
      this.dateModified,
      this.dateModifiedGmt,
      this.src,
      this.name,
      this.alt});

  Image.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    dateCreated = json['date_created'];
    dateCreatedGmt = json['date_created_gmt'];
    dateModified = json['date_modified'];
    dateModifiedGmt = json['date_modified_gmt'];
    src = json['src'];
    name = json['name'];
    alt = json['alt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['date_created'] = this.dateCreated;
    data['date_created_gmt'] = this.dateCreatedGmt;
    data['date_modified'] = this.dateModified;
    data['date_modified_gmt'] = this.dateModifiedGmt;
    data['src'] = this.src;
    data['name'] = this.name;
    data['alt'] = this.alt;
    return data;
  }
}
