///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class GetAllReviewModelDataLinksUp {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/6434"
}
*/

  String? href;

  GetAllReviewModelDataLinksUp({
    this.href,
  });
  GetAllReviewModelDataLinksUp.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class GetAllReviewModelDataLinksCollection {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews"
}
*/

  String? href;

  GetAllReviewModelDataLinksCollection({
    this.href,
  });
  GetAllReviewModelDataLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class GetAllReviewModelDataLinksSelf {
/*
{
  "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews/236"
}
*/

  String? href;

  GetAllReviewModelDataLinksSelf({
    this.href,
  });
  GetAllReviewModelDataLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class GetAllReviewModelDataLinks {
/*
{
  "self": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews/236"
    }
  ],
  "collection": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews"
    }
  ],
  "up": [
    {
      "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/6434"
    }
  ]
}
*/

  List<GetAllReviewModelDataLinksSelf?>? self;
  List<GetAllReviewModelDataLinksCollection?>? collection;
  List<GetAllReviewModelDataLinksUp?>? up;

  GetAllReviewModelDataLinks({
    this.self,
    this.collection,
    this.up,
  });
  GetAllReviewModelDataLinks.fromJson(Map<String, dynamic> json) {
    if (json['self'] != null) {
      final v = json['self'];
      final arr0 = <GetAllReviewModelDataLinksSelf>[];
      v.forEach((v) {
        arr0.add(GetAllReviewModelDataLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json['collection'] != null) {
      final v = json['collection'];
      final arr0 = <GetAllReviewModelDataLinksCollection>[];
      v.forEach((v) {
        arr0.add(GetAllReviewModelDataLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
    if (json['up'] != null) {
      final v = json['up'];
      final arr0 = <GetAllReviewModelDataLinksUp>[];
      v.forEach((v) {
        arr0.add(GetAllReviewModelDataLinksUp.fromJson(v));
      });
      up = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      final v = self;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['self'] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['collection'] = arr0;
    }
    if (up != null) {
      final v = up;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['up'] = arr0;
    }
    return data;
  }
}

class GetAllReviewModelDataReviewerAvatarUrls {
/*
{
  "24": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g",
  "48": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g",
  "96": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g"
}
*/

  String? the24;
  String? the48;
  String? the96;

  GetAllReviewModelDataReviewerAvatarUrls({
    this.the24,
    this.the48,
    this.the96,
  });
  GetAllReviewModelDataReviewerAvatarUrls.fromJson(Map<String, dynamic> json) {
    the24 = json['24']?.toString();
    the48 = json['48']?.toString();
    the96 = json['96']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['24'] = the24;
    data['48'] = the48;
    data['96'] = the96;
    return data;
  }
}

class GetAllReviewModelData {
/*
{
  "id": 236,
  "date_created": "2024-02-20T10:21:44",
  "date_created_gmt": "2024-02-20T10:21:44",
  "product_id": 6434,
  "product_name": "Private: WordPress Tee",
  "product_permalink": "https://localfirst.testdevteam.xyz/product/wordpress-tee/",
  "status": "approved",
  "reviewer": "Johsdn Doe",
  "reviewer_email": "johnds.doe@example.com",
  "review": "<p>Nicedsd album!</p>\n",
  "rating": 4,
  "verified": false,
  "reviewer_avatar_urls": {
    "24": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g",
    "48": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g",
    "96": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g"
  },
  "_links": {
    "self": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews/236"
      }
    ],
    "collection": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews"
      }
    ],
    "up": [
      {
        "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/6434"
      }
    ]
  }
}
*/

  num? id;
  String? dateCreated;
  String? dateCreatedGmt;
  num? productId;
  String? productName;
  String? productPermalink;
  String? status;
  String? reviewer;
  String? reviewerEmail;
  String? review;
  double? rating;
  bool? verified;
  GetAllReviewModelDataReviewerAvatarUrls? reviewerAvatarUrls;
  GetAllReviewModelDataLinks? Links;

  GetAllReviewModelData({
    this.id,
    this.dateCreated,
    this.dateCreatedGmt,
    this.productId,
    this.productName,
    this.productPermalink,
    this.status,
    this.reviewer,
    this.reviewerEmail,
    this.review,
    this.rating,
    this.verified,
    this.reviewerAvatarUrls,
    this.Links,
  });
  GetAllReviewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    dateCreated = json['date_created']?.toString();
    dateCreatedGmt = json['date_created_gmt']?.toString();
    productId = json['product_id']?.toInt();
    productName = json['product_name']?.toString();
    productPermalink = json['product_permalink']?.toString();
    status = json['status']?.toString();
    reviewer = json['reviewer']?.toString();
    reviewerEmail = json['reviewer_email']?.toString();
    review = json['review']?.toString();
    rating = json['rating']?.toDouble();
    verified = json['verified'];
    reviewerAvatarUrls = (json['reviewer_avatar_urls'] != null) ? GetAllReviewModelDataReviewerAvatarUrls.fromJson(json['reviewer_avatar_urls']) : null;
    Links = (json['_links'] != null) ? GetAllReviewModelDataLinks.fromJson(json['_links']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['date_created'] = dateCreated;
    data['date_created_gmt'] = dateCreatedGmt;
    data['product_id'] = productId;
    data['product_name'] = productName;
    data['product_permalink'] = productPermalink;
    data['status'] = status;
    data['reviewer'] = reviewer;
    data['reviewer_email'] = reviewerEmail;
    data['review'] = review;
    data['rating'] = rating;
    data['verified'] = verified;
    if (reviewerAvatarUrls != null) {
      data['reviewer_avatar_urls'] = reviewerAvatarUrls!.toJson();
    }
    if (Links != null) {
      data['_links'] = Links!.toJson();
    }
    return data;
  }
}

class GetAllReviewModel {
/*
{
  "success": true,
  "message": "Review list",
  "code": 200,
  "data": [
    {
      "id": 236,
      "date_created": "2024-02-20T10:21:44",
      "date_created_gmt": "2024-02-20T10:21:44",
      "product_id": 6434,
      "product_name": "Private: WordPress Tee",
      "product_permalink": "https://localfirst.testdevteam.xyz/product/wordpress-tee/",
      "status": "approved",
      "reviewer": "Johsdn Doe",
      "reviewer_email": "johnds.doe@example.com",
      "review": "<p>Nicedsd album!</p>\n",
      "rating": 4,
      "verified": false,
      "reviewer_avatar_urls": {
        "24": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g",
        "48": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g",
        "96": "https://secure.gravatar.com/avatar/6861032e5d013bc45c3414c40c594a91?s=90&d=mm&r=g"
      },
      "_links": {
        "self": [
          {
            "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews/236"
          }
        ],
        "collection": [
          {
            "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/reviews"
          }
        ],
        "up": [
          {
            "href": "https://localfirst.testdevteam.xyz/wp-json/wc/v3/products/6434"
          }
        ]
      }
    }
  ]
}
*/

  bool? success;
  String? message;
  num? code;
  List<GetAllReviewModelData?>? data;

  GetAllReviewModel({
    this.success,
    this.message,
    this.code,
    this.data,
  });
  GetAllReviewModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    code = json['code']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetAllReviewModelData>[];
      v.forEach((v) {
        arr0.add(GetAllReviewModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['code'] = code;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
