///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class LogInModelDataUser {
/*
{
  "ID": 96,
  "user_login": "kishan",
  "user_pass": "$2y$10$6EB1zvEdHn6aIGaVc9Ud5uD471RwAyqVJ3kQGTIVVdVTdA4mxGyEy",
  "user_nicename": "kishan",
  "user_email": "kishanandropedia@gmail.com",
  "user_url": "",
  "user_registered": "2024-02-14 04:24:00",
  "user_activation_key": "",
  "user_status": 0,
  "display_name": "kishan"
}
*/

  int? ID;
  String? userLogin;
  String? userPass;
  String? userNicename;
  String? userEmail;
  String? userUrl;
  String? userRegistered;
  String? userActivationKey;
  int? userStatus;
  String? displayName;

  LogInModelDataUser({
    this.ID,
    this.userLogin,
    this.userPass,
    this.userNicename,
    this.userEmail,
    this.userUrl,
    this.userRegistered,
    this.userActivationKey,
    this.userStatus,
    this.displayName,
  });

  LogInModelDataUser.fromJson(Map<String, dynamic> json) {
    ID = json['ID']?.toInt();
    userLogin = json['user_login']?.toString();
    userPass = json['user_pass']?.toString();
    userNicename = json['user_nicename']?.toString();
    userEmail = json['user_email']?.toString();
    userUrl = json['user_url']?.toString();
    userRegistered = json['user_registered']?.toString();
    userActivationKey = json['user_activation_key']?.toString();
    userStatus = json['user_status']?.toInt();
    displayName = json['display_name']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ID'] = ID;
    data['user_login'] = userLogin;
    data['user_pass'] = userPass;
    data['user_nicename'] = userNicename;
    data['user_email'] = userEmail;
    data['user_url'] = userUrl;
    data['user_registered'] = userRegistered;
    data['user_activation_key'] = userActivationKey;
    data['user_status'] = userStatus;
    data['display_name'] = displayName;
    return data;
  }
}

class LogInModelData {
/*
{
  "user": {
    "ID": 96,
    "user_login": "kishan",
    "user_pass": "$2y$10$6EB1zvEdHn6aIGaVc9Ud5uD471RwAyqVJ3kQGTIVVdVTdA4mxGyEy",
    "user_nicename": "kishan",
    "user_email": "kishanandropedia@gmail.com",
    "user_url": "",
    "user_registered": "2024-02-14 04:24:00",
    "user_activation_key": "",
    "user_status": 0,
    "display_name": "kishan"
  },
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsZmlyc3RhcGkudGVzdGRldnRlYW0ueHl6L2FwaS9sb2dpbiIsImlhdCI6MTcwNzg5NDE0MiwiZXhwIjoxNzA3ODk3NzQyLCJuYmYiOjE3MDc4OTQxNDIsImp0aSI6IkZBaWxKcFpEbm93bHFUeXciLCJzdWIiOiI5NiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xhJ1HLfAE1kjjjXQy6LSOeBAYVwPSV11ochRP64KCpg",
  "token_type": "bearer",
  "expires_in": 3600
}
*/

  LogInModelDataUser? user;
  String? accessToken;
  String? tokenType;
  int? expiresIn;

  LogInModelData({
    this.user,
    this.accessToken,
    this.tokenType,
    this.expiresIn,
  });

  LogInModelData.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? LogInModelDataUser.fromJson(json['user']) : null;
    accessToken = json['access_token']?.toString();
    tokenType = json['token_type']?.toString();
    expiresIn = json['expires_in']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['access_token'] = accessToken;
    data['token_type'] = tokenType;
    data['expires_in'] = expiresIn;
    return data;
  }
}

class LogInModel {
/*
{
  "success": true,
  "message": "Login Successfully",
  "code": 200,
  "data": {
    "user": {
      "ID": 96,
      "user_login": "kishan",
      "user_pass": "$2y$10$6EB1zvEdHn6aIGaVc9Ud5uD471RwAyqVJ3kQGTIVVdVTdA4mxGyEy",
      "user_nicename": "kishan",
      "user_email": "kishanandropedia@gmail.com",
      "user_url": "",
      "user_registered": "2024-02-14 04:24:00",
      "user_activation_key": "",
      "user_status": 0,
      "display_name": "kishan"
    },
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvY2FsZmlyc3RhcGkudGVzdGRldnRlYW0ueHl6L2FwaS9sb2dpbiIsImlhdCI6MTcwNzg5NDE0MiwiZXhwIjoxNzA3ODk3NzQyLCJuYmYiOjE3MDc4OTQxNDIsImp0aSI6IkZBaWxKcFpEbm93bHFUeXciLCJzdWIiOiI5NiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xhJ1HLfAE1kjjjXQy6LSOeBAYVwPSV11ochRP64KCpg",
    "token_type": "bearer",
    "expires_in": 3600
  }
}
*/

  bool? success;
  String? message;
  int? code;
  LogInModelData? data;

  LogInModel({
    this.success,
    this.message,
    this.code,
    this.data,
  });

  LogInModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    code = json['code']?.toInt();
    data = (json['data'] != null) ? LogInModelData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['code'] = code;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
