///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class SelectLocationModelDataLocationResultsPlusCode {
/*
{
  "compound_code": "Q572+QQ Bhavnagar, Gujarat, India",
  "global_code": "7JHJQ572+QQ"
}
*/

  String? compoundCode;
  String? globalCode;

  SelectLocationModelDataLocationResultsPlusCode({
    this.compoundCode,
    this.globalCode,
  });
  SelectLocationModelDataLocationResultsPlusCode.fromJson(Map<String, dynamic> json) {
    compoundCode = json['compound_code']?.toString();
    globalCode = json['global_code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['compound_code'] = compoundCode;
    data['global_code'] = globalCode;
    return data;
  }
}

class SelectLocationModelDataLocationResultsGeometryViewportSouthwest {
/*
{
  "lat": 21.76312301970849,
  "lng": 72.1505806197085
}
*/

  double? lat;
  double? lng;

  SelectLocationModelDataLocationResultsGeometryViewportSouthwest({
    this.lat,
    this.lng,
  });
  SelectLocationModelDataLocationResultsGeometryViewportSouthwest.fromJson(Map<String, dynamic> json) {
    lat = json['lat']?.toDouble();
    lng = json['lng']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lat'] = lat;
    data['lng'] = lng;
    return data;
  }
}

class SelectLocationModelDataLocationResultsGeometryViewportNortheast {
/*
{
  "lat": 21.7658209802915,
  "lng": 72.15327858029151
}
*/

  double? lat;
  double? lng;

  SelectLocationModelDataLocationResultsGeometryViewportNortheast({
    this.lat,
    this.lng,
  });
  SelectLocationModelDataLocationResultsGeometryViewportNortheast.fromJson(Map<String, dynamic> json) {
    lat = json['lat']?.toDouble();
    lng = json['lng']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lat'] = lat;
    data['lng'] = lng;
    return data;
  }
}

class SelectLocationModelDataLocationResultsGeometryViewport {
/*
{
  "northeast": {
    "lat": 21.7658209802915,
    "lng": 72.15327858029151
  },
  "southwest": {
    "lat": 21.76312301970849,
    "lng": 72.1505806197085
  }
}
*/

  SelectLocationModelDataLocationResultsGeometryViewportNortheast? northeast;
  SelectLocationModelDataLocationResultsGeometryViewportSouthwest? southwest;

  SelectLocationModelDataLocationResultsGeometryViewport({
    this.northeast,
    this.southwest,
  });
  SelectLocationModelDataLocationResultsGeometryViewport.fromJson(Map<String, dynamic> json) {
    northeast = (json['northeast'] != null) ? SelectLocationModelDataLocationResultsGeometryViewportNortheast.fromJson(json['northeast']) : null;
    southwest = (json['southwest'] != null) ? SelectLocationModelDataLocationResultsGeometryViewportSouthwest.fromJson(json['southwest']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (northeast != null) {
      data['northeast'] = northeast!.toJson();
    }
    if (southwest != null) {
      data['southwest'] = southwest!.toJson();
    }
    return data;
  }
}

class SelectLocationModelDataLocationResultsGeometryLocation {
/*
{
  "lat": 21.764472,
  "lng": 72.1519296
}
*/

  double? lat;
  double? lng;

  SelectLocationModelDataLocationResultsGeometryLocation({
    this.lat,
    this.lng,
  });
  SelectLocationModelDataLocationResultsGeometryLocation.fromJson(Map<String, dynamic> json) {
    lat = json['lat']?.toDouble();
    lng = json['lng']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lat'] = lat;
    data['lng'] = lng;
    return data;
  }
}

class SelectLocationModelDataLocationResultsGeometry {
/*
{
  "location": {
    "lat": 21.764472,
    "lng": 72.1519296
  },
  "location_type": "ROOFTOP",
  "viewport": {
    "northeast": {
      "lat": 21.7658209802915,
      "lng": 72.15327858029151
    },
    "southwest": {
      "lat": 21.76312301970849,
      "lng": 72.1505806197085
    }
  }
}
*/

  SelectLocationModelDataLocationResultsGeometryLocation? location;
  String? locationType;
  SelectLocationModelDataLocationResultsGeometryViewport? viewport;

  SelectLocationModelDataLocationResultsGeometry({
    this.location,
    this.locationType,
    this.viewport,
  });
  SelectLocationModelDataLocationResultsGeometry.fromJson(Map<String, dynamic> json) {
    location = (json['location'] != null) ? SelectLocationModelDataLocationResultsGeometryLocation.fromJson(json['location']) : null;
    locationType = json['location_type']?.toString();
    viewport = (json['viewport'] != null) ? SelectLocationModelDataLocationResultsGeometryViewport.fromJson(json['viewport']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['location_type'] = locationType;
    if (viewport != null) {
      data['viewport'] = viewport!.toJson();
    }
    return data;
  }
}

class SelectLocationModelDataLocationResultsAddressComponents {
/*
{
  "long_name": "1830",
  "short_name": "1830",
  "types": [
    "premise"
  ]
}
*/

  String? longName;
  String? shortName;
  List<String?>? types;

  SelectLocationModelDataLocationResultsAddressComponents({
    this.longName,
    this.shortName,
    this.types,
  });
  SelectLocationModelDataLocationResultsAddressComponents.fromJson(Map<String, dynamic> json) {
    longName = json['long_name']?.toString();
    shortName = json['short_name']?.toString();
    if (json['types'] != null) {
      final v = json['types'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      types = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['long_name'] = longName;
    data['short_name'] = shortName;
    if (types != null) {
      final v = types;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['types'] = arr0;
    }
    return data;
  }
}

class SelectLocationModelDataLocationResults {
/*
{
  "address_components": [
    {
      "long_name": "1830",
      "short_name": "1830",
      "types": [
        "premise"
      ]
    }
  ],
  "formatted_address": "1830, near Teja Bhakt Tempal, Pragati Nagar, Takhteshwar Plots, Bhavnagar, Gujarat 364001, India",
  "geometry": {
    "location": {
      "lat": 21.764472,
      "lng": 72.1519296
    },
    "location_type": "ROOFTOP",
    "viewport": {
      "northeast": {
        "lat": 21.7658209802915,
        "lng": 72.15327858029151
      },
      "southwest": {
        "lat": 21.76312301970849,
        "lng": 72.1505806197085
      }
    }
  },
  "place_id": "ChIJzcTiFXtaXzkRpDXdcdC4c9U",
  "plus_code": {
    "compound_code": "Q572+QQ Bhavnagar, Gujarat, India",
    "global_code": "7JHJQ572+QQ"
  },
  "types": [
    "street_address"
  ]
}
*/

  List<SelectLocationModelDataLocationResultsAddressComponents?>? addressComponents;
  String? formattedAddress;
  SelectLocationModelDataLocationResultsGeometry? geometry;
  String? placeId;
  SelectLocationModelDataLocationResultsPlusCode? plusCode;
  List<String?>? types;

  SelectLocationModelDataLocationResults({
    this.addressComponents,
    this.formattedAddress,
    this.geometry,
    this.placeId,
    this.plusCode,
    this.types,
  });
  SelectLocationModelDataLocationResults.fromJson(Map<String, dynamic> json) {
    if (json['address_components'] != null) {
      final v = json['address_components'];
      final arr0 = <SelectLocationModelDataLocationResultsAddressComponents>[];
      v.forEach((v) {
        arr0.add(SelectLocationModelDataLocationResultsAddressComponents.fromJson(v));
      });
      addressComponents = arr0;
    }
    formattedAddress = json['formatted_address']?.toString();
    geometry = (json['geometry'] != null) ? SelectLocationModelDataLocationResultsGeometry.fromJson(json['geometry']) : null;
    placeId = json['place_id']?.toString();
    plusCode = (json['plus_code'] != null) ? SelectLocationModelDataLocationResultsPlusCode.fromJson(json['plus_code']) : null;
    if (json['types'] != null) {
      final v = json['types'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      types = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (addressComponents != null) {
      final v = addressComponents;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['address_components'] = arr0;
    }
    data['formatted_address'] = formattedAddress;
    if (geometry != null) {
      data['geometry'] = geometry!.toJson();
    }
    data['place_id'] = placeId;
    if (plusCode != null) {
      data['plus_code'] = plusCode!.toJson();
    }
    if (types != null) {
      final v = types;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['types'] = arr0;
    }
    return data;
  }
}

class SelectLocationModelDataLocationPlusCode {
/*
{
  "compound_code": "Q572+QQR Bhavnagar, Gujarat, India",
  "global_code": "7JHJQ572+QQR"
}
*/

  String? compoundCode;
  String? globalCode;

  SelectLocationModelDataLocationPlusCode({
    this.compoundCode,
    this.globalCode,
  });
  SelectLocationModelDataLocationPlusCode.fromJson(Map<String, dynamic> json) {
    compoundCode = json['compound_code']?.toString();
    globalCode = json['global_code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['compound_code'] = compoundCode;
    data['global_code'] = globalCode;
    return data;
  }
}

class SelectLocationModelDataLocation {
/*
{
  "plus_code": {
    "compound_code": "Q572+QQR Bhavnagar, Gujarat, India",
    "global_code": "7JHJQ572+QQR"
  },
  "results": [
    {
      "address_components": [
        {
          "long_name": "1830",
          "short_name": "1830",
          "types": [
            "premise"
          ]
        }
      ],
      "formatted_address": "1830, near Teja Bhakt Tempal, Pragati Nagar, Takhteshwar Plots, Bhavnagar, Gujarat 364001, India",
      "geometry": {
        "location": {
          "lat": 21.764472,
          "lng": 72.1519296
        },
        "location_type": "ROOFTOP",
        "viewport": {
          "northeast": {
            "lat": 21.7658209802915,
            "lng": 72.15327858029151
          },
          "southwest": {
            "lat": 21.76312301970849,
            "lng": 72.1505806197085
          }
        }
      },
      "place_id": "ChIJzcTiFXtaXzkRpDXdcdC4c9U",
      "plus_code": {
        "compound_code": "Q572+QQ Bhavnagar, Gujarat, India",
        "global_code": "7JHJQ572+QQ"
      },
      "types": [
        "street_address"
      ]
    }
  ],
  "status": "OK"
}
*/

  SelectLocationModelDataLocationPlusCode? plusCode;
  List<SelectLocationModelDataLocationResults?>? results;
  String? status;

  SelectLocationModelDataLocation({
    this.plusCode,
    this.results,
    this.status,
  });
  SelectLocationModelDataLocation.fromJson(Map<String, dynamic> json) {
    plusCode = (json['plus_code'] != null) ? SelectLocationModelDataLocationPlusCode.fromJson(json['plus_code']) : null;
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <SelectLocationModelDataLocationResults>[];
      v.forEach((v) {
        arr0.add(SelectLocationModelDataLocationResults.fromJson(v));
      });
      results = arr0;
    }
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (plusCode != null) {
      data['plus_code'] = plusCode!.toJson();
    }
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    data['status'] = status;
    return data;
  }
}

class SelectLocationModelData {
/*
{
  "location": {
    "plus_code": {
      "compound_code": "Q572+QQR Bhavnagar, Gujarat, India",
      "global_code": "7JHJQ572+QQR"
    },
    "results": [
      {
        "address_components": [
          {
            "long_name": "1830",
            "short_name": "1830",
            "types": [
              "premise"
            ]
          }
        ],
        "formatted_address": "1830, near Teja Bhakt Tempal, Pragati Nagar, Takhteshwar Plots, Bhavnagar, Gujarat 364001, India",
        "geometry": {
          "location": {
            "lat": 21.764472,
            "lng": 72.1519296
          },
          "location_type": "ROOFTOP",
          "viewport": {
            "northeast": {
              "lat": 21.7658209802915,
              "lng": 72.15327858029151
            },
            "southwest": {
              "lat": 21.76312301970849,
              "lng": 72.1505806197085
            }
          }
        },
        "place_id": "ChIJzcTiFXtaXzkRpDXdcdC4c9U",
        "plus_code": {
          "compound_code": "Q572+QQ Bhavnagar, Gujarat, India",
          "global_code": "7JHJQ572+QQ"
        },
        "types": [
          "street_address"
        ]
      }
    ],
    "status": "OK"
  }
}
*/

  SelectLocationModelDataLocation? location;

  SelectLocationModelData({
    this.location,
  });
  SelectLocationModelData.fromJson(Map<String, dynamic> json) {
    location = (json['location'] != null) ? SelectLocationModelDataLocation.fromJson(json['location']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (location != null) {
      data['location'] = location!.toJson();
    }
    return data;
  }
}

class SelectLocationModel {
/*
{
  "success": true,
  "message": "Get Location Successfully",
  "code": 200,
  "data": {
    "location": {
      "plus_code": {
        "compound_code": "Q572+QQR Bhavnagar, Gujarat, India",
        "global_code": "7JHJQ572+QQR"
      },
      "results": [
        {
          "address_components": [
            {
              "long_name": "1830",
              "short_name": "1830",
              "types": [
                "premise"
              ]
            }
          ],
          "formatted_address": "1830, near Teja Bhakt Tempal, Pragati Nagar, Takhteshwar Plots, Bhavnagar, Gujarat 364001, India",
          "geometry": {
            "location": {
              "lat": 21.764472,
              "lng": 72.1519296
            },
            "location_type": "ROOFTOP",
            "viewport": {
              "northeast": {
                "lat": 21.7658209802915,
                "lng": 72.15327858029151
              },
              "southwest": {
                "lat": 21.76312301970849,
                "lng": 72.1505806197085
              }
            }
          },
          "place_id": "ChIJzcTiFXtaXzkRpDXdcdC4c9U",
          "plus_code": {
            "compound_code": "Q572+QQ Bhavnagar, Gujarat, India",
            "global_code": "7JHJQ572+QQ"
          },
          "types": [
            "street_address"
          ]
        }
      ],
      "status": "OK"
    }
  }
}
*/

  bool? success;
  String? message;
  int? code;
  SelectLocationModelData? data;

  SelectLocationModel({
    this.success,
    this.message,
    this.code,
    this.data,
  });
  SelectLocationModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    code = json['code']?.toInt();
    data = (json['data'] != null) ? SelectLocationModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['code'] = code;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
